name: CI/CD Pipeline Docker Hub

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build dan Push Image
        run: |
          # Mengubah username jadi kecil biar gak error
          USER_NAME=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=$USER_NAME/laprak_8_cloud:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME